import { auth } from '@/auth';
import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<SessionProvider session={session}>
			<html lang="en">
				<body className={`antialiased`}>
					<Navbar /> {children}
				</body>
			</html>
		</SessionProvider>
	);
}
