// import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
// import { SessionProvider } from 'next-auth/react';
import './globals.css';

export const metadata: Metadata = {
	title: 'Palabunutan - ',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// <SessionProvider session={session}>
		<html lang="en">
			<body className={`antialiased bg-[#18191A] text-white`}>
				{/* <Navbar /> */}
				{children}
			</body>
		</html>
		// </SessionProvider>
	);
}
